"""
Data loading utilities for LANL and synthetic data
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from pathlib import Path
import logging
from tqdm import tqdm

from .config import (
    DATA_PATH, LANL_COLUMNS, LANL_SAMPLE_SIZE,
    SYNTHETIC_PATH, AFTER_HOURS_START, AFTER_HOURS_END
)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class LANLDataLoader:
    """Load and preprocess LANL authentication dataset"""
    
    def __init__(self, file_path=DATA_PATH, sample_size=LANL_SAMPLE_SIZE):
        self.file_path = Path(file_path)
        self.sample_size = sample_size
        
    def load(self):
        """
        Load LANL dataset from CSV/TXT file
        
        Returns:
            pd.DataFrame: Processed authentication logs
        """
        if not self.file_path.exists():
            logger.error(f"LANL file not found at: {self.file_path}")
            logger.info("Please place your LANL dataset at data/raw/lanl_auth_logs.txt")
            return None
        
        logger.info(f"Loading LANL data from {self.file_path}...")
        
        try:
            # Read CSV (LANL uses comma-separated)
            df = pd.read_csv(
                self.file_path,
                names=LANL_COLUMNS,
                nrows=self.sample_size,
                low_memory=False
            )
            
            logger.info(f"Loaded {len(df)} authentication records")
            
            # Preprocess
            df = self._preprocess(df)
            
            logger.info(f"Preprocessing complete. Final shape: {df.shape}")
            return df
            
        except Exception as e:
            logger.error(f"Error loading LANL data: {e}")
            return None
    
    def _preprocess(self, df):
        """
        Preprocess LANL data: convert timestamps, extract features, clean data
        
        Args:
            df (pd.DataFrame): Raw LANL data
            
        Returns:
            pd.DataFrame: Preprocessed data
        """
        logger.info("Preprocessing LANL data...")
        
        # Convert time (LANL uses seconds since epoch)
        df['timestamp'] = pd.to_datetime(df['time'], unit='s')
        df['hour'] = df['timestamp'].dt.hour
        df['day_of_week'] = df['timestamp'].dt.dayofweek
        df['is_weekend'] = (df['day_of_week'] >= 5).astype(int)
        
        # After-hours indicator
        df['is_after_hours'] = (
            (df['hour'] < AFTER_HOURS_END) | 
            (df['hour'] >= AFTER_HOURS_START)
        ).astype(int)
        
        # Success/failure
        df['is_failure'] = (~df['success'].str.contains('Success', na=False)).astype(int)
        
        # Lateral movement indicator (user accessing different computers)
        df['is_lateral_movement'] = (
            df['source_computer'] != df['destination_computer']
        ).astype(int)
        
        # Clean user/computer IDs (remove domain prefixes)
        df['user_id'] = df['source_user'].str.split('@').str[0]
        df['source_computer'] = df['source_computer'].str.split('$').str[0]
        df['destination_computer'] = df['destination_computer'].str.split('$').str[0]
        
        # Remove rows with missing critical data
        df = df.dropna(subset=['user_id', 'timestamp'])
        
        # Sort by timestamp
        df = df.sort_values('timestamp').reset_index(drop=True)
        
        return df


class SyntheticDataLoader:
    """Load synthetic data generated by Faker"""
    
    def __init__(self, file_path=SYNTHETIC_PATH):
        self.file_path = Path(file_path)
    
    def load(self):
        """
        Load synthetic data from CSV
        
        Returns:
            pd.DataFrame: Synthetic authentication logs
        """
        if not self.file_path.exists():
            logger.warning(f"Synthetic data not found at: {self.file_path}")
            logger.info("Run 'python -m src.data_generator' to create synthetic data")
            return None
        
        logger.info(f"Loading synthetic data from {self.file_path}...")
        
        try:
            df = pd.read_csv(self.file_path, parse_dates=['timestamp'])
            logger.info(f"Loaded {len(df)} synthetic records")
            return df
        except Exception as e:
            logger.error(f"Error loading synthetic data: {e}")
            return None


def combine_datasets(lanl_df, synthetic_df):
    """
    Combine LANL and synthetic datasets
    
    Args:
        lanl_df (pd.DataFrame): LANL authentication logs
        synthetic_df (pd.DataFrame): Synthetic logs
        
    Returns:
        pd.DataFrame: Combined dataset
    """
    if lanl_df is None and synthetic_df is None:
        raise ValueError("Both datasets are None. Cannot proceed.")
    
    if lanl_df is None:
        logger.info("Using only synthetic data")
        return synthetic_df
    
    if synthetic_df is None:
        logger.info("Using only LANL data")
        return lanl_df
    
    logger.info("Combining LANL and synthetic datasets...")
    
    # Ensure common columns
    common_cols = list(set(lanl_df.columns) & set(synthetic_df.columns))
    
    combined = pd.concat([
        lanl_df[common_cols],
        synthetic_df[common_cols]
    ], ignore_index=True)
    
    combined = combined.sort_values('timestamp').reset_index(drop=True)
    
    logger.info(f"Combined dataset: {len(combined)} records")
    logger.info(f"LANL: {len(lanl_df)}, Synthetic: {len(synthetic_df)}")
    
    return combined


def load_all_data(use_lanl=True, use_synthetic=True):
    """
    Convenience function to load all available data
    
    Args:
        use_lanl (bool): Load LANL data
        use_synthetic (bool): Load synthetic data
        
    Returns:
        pd.DataFrame: Combined dataset
    """
    lanl_df = None
    synthetic_df = None
    
    if use_lanl:
        lanl_loader = LANLDataLoader()
        lanl_df = lanl_loader.load()
    
    if use_synthetic:
        synthetic_loader = SyntheticDataLoader()
        synthetic_df = synthetic_loader.load()
    
    return combine_datasets(lanl_df, synthetic_df)


def load_lanl_data(filepath):
    # Implement LANL data loading here
    pass

def load_synthetic_data(filepath):
    # Implement synthetic data loading here
    pass


if __name__ == "__main__":
    # Test loading
    df = load_all_data(use_lanl=True, use_synthetic=True)
    
    if df is not None:
        print("\n=== Dataset Summary ===")
        print(f"Total records: {len(df)}")
        print(f"Date range: {df['timestamp'].min()} to {df['timestamp'].max()}")
        print(f"Unique users: {df['user_id'].nunique()}")
        print(f"\nSample data:")
        print(df.head())